### ISSUE TITLE
./configure Error when trying to install on macOS

### ISSUE THREAD

**Issue by wasdee** [tlwg/thpronun#1]
After trial-and-error of the attempt to install this on macOS, everything was going well when installing the library following [this](https://github.com/wasdee/thpronun/blob/master/INSTALL.md) instruction.

On ``./configure`` step, I obstructed by this error message. For 40 min, I had went thru some of the code to figure out where is the cause of this error. Yet I haven't found.

Below is the recent line of error.
```
/bin/sh ../libtool  --tag=CC   --mode=link gcc  -g -O2   -o gen-lookup-dict gen-lookup-dict.o -L/opt/local/lib -ldatrie
libtool: link: gcc -g -O2 -o gen-lookup-dict gen-lookup-dict.o  -L/opt/local/lib -ldatrie
Undefined symbols for architecture x86_64:
  "_libiconv", referenced from:
      _ReadInput in gen-lookup-dict.o
  "_libiconv_close", referenced from:
      _GenDict in gen-lookup-dict.o
  "_libiconv_open", referenced from:
      _GenDict in gen-lookup-dict.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [gen-lookup-dict] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1
```

**Comment by wasdee** [comment]
from [this](https://github.com/alexcrichton/git2-rs/issues/263#issuecomment-369420373)
```
  - archs:           [ i386 ]
    symbols:         [ _libiconv, _libiconv_close, _libiconv_open, _libiconvctl, 
                       _libiconvlist ]
  - archs:           [ i386, x86_64 ]
    symbols:         [ ___iconv_2VersionNumber, ___iconv_2VersionString, __libiconv_version, 
                       _aliases2_lookup, _aliases_lookup, _iconv, _iconv_canonicalize, 
                       _iconv_close, _iconv_open, _iconvctl, _iconvlist, _libiconv_relocate, 
                       _libiconv_set_relocation_prefix, _locale_charset, _utf8_decodestr, 
                       _utf8_encodestr, _utf_extrabytes ]
```
The 3 missing symbols (_libiconv, _libiconv_close, and _libiconv_open) are declared as being present in i386 but not x86_64. 

i think we just need a way to specify the iconv library to use so, I follow [this](https://nlfiedler.github.io/2014/07/25/Mac_Git_Libiconv.html) and found that I am not able to ``libiconv`` from hombrew or macport using something like 
```
./configure --with-iconv=/usr/local
```

**Comment by thep** [comment]
And trying to support `libiconv` fallback properly appears to be [too costly](https://lists.gnu.org/archive/html/bug-gettext/2011-10/msg00012.html), esp. when all we need is read UTF-8 input.

I think I'll just replace `iconv()` calls with a simple UTF-8 reader, then.
